AgenciaViajes.MVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AgenciaViajes.MVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

AgenciaViajes.MVC/Controllers/ViajeroController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AgenciaViajes.MVC.Controllers
{
    public class ViajeroController : Controller
    {
        // GET: Viajero
        public ActionResult Viajero()
        {
            return View();
        }
        [HttpGet]
        public ActionResult EditViajero(int IdViajero)
        {
            return View(IdViajero);
        }
        [HttpGet]
        public ActionResult DeleteViajero(int IdViajero)
        {
            return View(IdViajero);
        }

        [HttpGet]
        public ActionResult CreateViajero()
        {
            return View();
        }
    }
}

AgenciaViajes.MVC/Controllers/Viajeros_ViajesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AgenciaViajes.MVC.Controllers
{
    public class Viajeros_ViajesController : Controller
    {
        // GET: Viajeros_Viajes
        public ActionResult ViajerosViajes()
        {
            return View();
        }

        public ActionResult CreateViajeroViaje()
        {
            return View();
        }

        public ActionResult EditViajeroViaje(int IdViaje)
        {
            return View(IdViaje);
        }

        public ActionResult DeleteViajeroViaje(int IdViaje)
        {
            return View(IdViaje);
        }
    }
}

AgenciaViajes.MVC/Controllers/ViajesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AgenciaViajes.MVC.Controllers
{
    public class ViajesController : Controller
    {
        // GET: Viajes
        public ActionResult Viajes()
        {
            return View();
        }
        [HttpGet]
        public ActionResult CreateViajes()
        {
            return View();
        }
        [HttpGet]
        public ActionResult EditViajes(int IdViaje)
        {
            return View(IdViaje);
        }
        [HttpGet]
        public ActionResult DeleteViajes(int IdViaje)
        {
            return View(IdViaje);
        }
       

    }
}

AgenciaViajes.MVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h2>Sistema de gestión de asignación de viajes</h2>
    
</div>

AgenciaViajes.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Gestión de Viajes </title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Getión de Viajes", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Viajero", "Viajero", "Viajero")</li>
                    <li>@Html.ActionLink("Viajes", "Viajes", "Viajes")</li>
                    <li>@Html.ActionLink("Gestor de viajes", "ViajerosViajes", "Viajeros_Viajes")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Gestión de Viajes</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

AgenciaViajes.MVC/Views/Viajero/CreateViajero.cshtml
@{
    ViewBag.Title = "CreateViajero";
    @*  *@}

<h2>Crear nuevo Viajero</h2>
<form id="viajeroForm" data-toggle="validator" role="form">
    <fieldset>
        <legend><h5>Viajero</h5></legend>
        <div class="form-group">
            <label class="control-label ">Nombre:</label>
            <input id="txtNombre" type="text" class="form-control removeLater" placeholder="Nombre" required />
        </div>
        <div class="form-group">
            <label class="control-label ">Cédula:</label>
            <input id="txtCedula" type="text" class="form-control removeLater" placeholder="Cédula" required />
        </div>
    </fieldset>

    <fieldset>
        <legend><h5>Dirección</h5></legend>
        <div class="form-group">
            <label class="control-label ">Dirección1:</label>
            <input id="txtDireccion1" type="text" class="form-control removeLater" placeholder="Dirección1" required />
        </div>
        <div class="form-group">
            <label class="control-label ">Dirección2:</label>
            <input id="txtDireccion2" type="text" class="form-control removeLater" placeholder="Dirección2" />
        </div>

        <div class="form-group">
            <label class="control-label ">Ciudad:</label>
            <input id="txtCiudad" type="text" class="form-control removeLater" placeholder="Ciudad" required />
        </div>
        <div class="form-group">
            <label class="control-label ">Estado:</label>
            <input id="txtEstado" type="text" class="form-control removeLater" placeholder="Estado" required />
        </div>
        <div class="form-group">
            <label class="control-label ">Teléfono Móvil:</label>
            <input id="txtTelefonoMovil" type="text" class="form-control removeLater" placeholder="Teléfono Móvil" required />
        </div>
        <div class="form-group">
            <label class="control-label ">Teléfono Fijo:</label>
            <input id="txtTelefonoFijo" type="text" class="form-control removeLater" placeholder="Teléfono Fijo" />
        </div>


    </fieldset>


    <div class="form-group float-lg-right">
        <button id="btnGuardar" type="submit" class="btn btn-success" value="Guardar">Guardar</button>
        <a id="btnCancelar" href="/Viajero/Viajero" class="btn btn-primary">Cancelar</a>
    </div>

</form>

@section Scripts
{
    <script type="text/JavaScript">
        $(document).ready(function () {

            $("#btnGuardar").click(function () {
                var nombre = $('#txtNombre').val();
                var cedula = $('#txtCedula').val();
                var direccion1 = $('#txtDireccion1').val();
                var direccion2 = $('#txtDireccion2').val();
                var ciudad = $("#txtCiudad").val();
                var estado = $("#txtEstado").val();
                var telefonoMovil = $("#txtTelefonoMovil").val();
                var telefonoFijo = $("#txtTelefonoFijo").val();

                let objViajero = {
                    nombre: nombre,
                    cedula: cedula,
                    direccion: {
                        direccion1: direccion1,
                        direccion2: direccion2,
                        ciudad: ciudad,
                        estado: estado,
                        telefonoMovil: telefonoMovil,
                        telefonoFijo: telefonoFijo
                    }
                };

                InsertarViajero(objViajero);
                $(".removeLater").val('');

            });
        });
        function InsertarViajero(viajero1) {
            var viajero = JSON.stringify(viajero1);
            $.ajax({
                url: 'https://localhost:44380/api/Viajero/InsertViajero',
                type: "POST",
                data: viajero, //JSON.stringify({ viajero: viajero }),
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                error: function (response) {
                    alert(response.responseText);
                    sendMessageClient("", false);
                },
                success: function (formato) {
                    $(".removeLater").val('');
                    sendMessageClient(formato.d, true);
                }
            });
        }

        function Go() {
            window.location.href = '/Viajero/Viajero/';
        }
    </script>
}

AgenciaViajes.MVC/Views/Viajero/DeleteViajero.cshtml
@{
    ViewBag.Title = "DeleteViajero";
}
<h2>Eliminar Viajero</h2>
<input type="hidden" id="IdViajero" value="@Model" />
<form id="viajeroForm">
    <fieldset>
        <legend><h5>Viajero</h5></legend>
        <div class="form-group">
            <label class="control-label ">Nombre:</label>
            <input id="txtNombre" type="text" class="form-control removeLater" readonly />
        </div>
        <div class="form-group">
            <label class="control-label ">Cédula:</label>
            <input id="txtCedula" type="text" class="form-control removeLater" readonly />
        </div>
    </fieldset>

    <fieldset>
        <legend><h5>Dirección</h5></legend>
        <div class="form-group">
            <label class="control-label ">Dirección1:</label>
            <input id="txtDireccion1" type="text" class="form-control removeLater" readonly />
        </div>
        <div class="form-group">
            <label class="control-label ">Dirección2:</label>
            <input id="txtDireccion2" type="text" class="form-control removeLater" readonly />
        </div>
        <div class="form-group">
            <label class="control-label ">Ciudad:</label>
            <input id="txtCiudad" type="text" class="form-control removeLater" readonly />
        </div>
        <div class="form-group">
            <label class="control-label ">Estado:</label>
            <input id="txtEstado" type="text" class="form-control removeLater" readonly />
        </div>
        <div class="form-group">
            <label class="control-label ">Teléfono Móvil:</label>
            <input id="txtTelefonoMovil" type="text" class="form-control removeLater" readonly />
        </div>
        <div class="form-group">
            <label class="control-label ">Teléfono Fijo:</label>
            <input id="txtTelefonoFijo" type="text" class="form-control removeLater" readonly />
        </div>


    </fieldset>

    <div class="form-group">
        <input id="btnEliminar" type="button" class="btn btn-success" value="Eliminar" />
        <a href="/Viajero/Viajero" class="btn btn-primary">Cancelar</a>
        @*<input id="btnCancelar" type="button" class="btn btn-primary" value="Cancelar" />*@
    </div>

</form>
@section Scripts
{
    <script type="text/JavaScript">
        $(document).ready(function () {

            var idViajero2 = $("#IdViajero").val();
            GetViajeroByIdViajero(idViajero2);


            $("#btnEliminar").click(function () {

                DeleteViajero($("#IdViajero").val());
                Go();
            });
           


        });
        function DeleteViajero(IdViajero) {
            var break2 = "stop";

            $.ajax({
                url: 'https://localhost:44380/api/Viajero/DeleteViajero2/?IdViajero=' + IdViajero,
                type: "GET",
                data: IdViajero,
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                error: function (response) {
                    alert(response.responseText);
                    sendMessageClient("", false);
                },
                success: function (viajero) {


                }
            });
        }

        //Obtiene una instancia del objeto Viajero por el IdViajero
        function GetViajeroByIdViajero(IdViajero) {

            $.ajax({
                url: 'https://localhost:44380/api/Viajero/GetViajerosByIdViajero/?IdViajero=' + IdViajero,
                type: "GET",
                data: IdViajero,
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                error: function (response) {
                    alert(response.responseText);
                    sendMessageClient("", false);
                },
                success: function (viajero) {
                    $('#txtNombre').val(viajero.Nombre);
                    $('#txtCedula').val(viajero.Cedula);
                    $('#txtDireccion1').val(viajero.Direccion.Direccion1);
                    $('#txtDireccion2').val(viajero.Direccion.Direccion2);
                    $("#txtCiudad").val(viajero.Direccion.Ciudad);
                    $("#txtEstado").val(viajero.Direccion.Estado);
                    $("#txtTelefonoMovil").val(viajero.Direccion.TelefonoMovil);
                    $("#txtTelefonoFijo").val(viajero.Direccion.TelefonoFijo);

                }
            });
        }

        function Go() {
            window.location.href = '/Viajero/Viajero/';
        }
    </script>
}

AgenciaViajes.MVC/Views/Viajero/EditViajero.cshtml
@{
    ViewBag.Title = "EditViajero";
}

<input type="hidden" id="IdViajero" value="@Model" />
<form id="viajeroForm">
    <div class="container">

        <fieldset>
            <legend><h5>Editar Viajero</h5></legend>
            <div class="form-group">
                <label class="control-label ">Nombre:</label>
                <input id="txtNombre" type="text" class="form-control removeLater" placeholder="Nombre" required />
            </div>
            <div class="form-group">
                <label class="control-label ">Cédula:</label>
                <input id="txtCedula" type="text" class="form-control removeLater" placeholder="Cédula" required />
            </div>
        </fieldset>


        <fieldset>
            <legend><h5>Dirección</h5></legend>
            <div class="form-group">
                <label class="control-label ">Dirección1:</label>
                <input id="txtDireccion1" type="text" class="form-control removeLater" placeholder="Dirección1" required />
            </div>
            <div class="form-group">
                <label class="control-label ">Dirección2:</label>
                <input id="txtDireccion2" type="text" class="form-control removeLater" placeholder="Dirección2" />
            </div>
            <div class="form-group">
                <label class="control-label ">Ciudad:</label>
                <input id="txtCiudad" type="text" class="form-control removeLater" placeholder="Ciudad" required />
            </div>
            <div class="form-group">
                <label class="control-label ">Estado:</label>
                <input id="txtEstado" type="text" class="form-control removeLater" placeholder="Estado" required />
            </div>
            <div class="form-group">
                <label class="control-label ">Teléfono Móvil:</label>
                <input id="txtTelefonoMovil" type="text" class="form-control removeLater" placeholder="Teléfono Móvil" required />
            </div>
            <div class="form-group">
                <label class="control-label ">Teléfono Fijo:</label>
                <input id="txtTelefonoFijo" type="text" class="form-control removeLater" placeholder="Teléfono Fijo" />
            </div>


        </fieldset>


        <div class="form-group">
            <input id="btnGuardar" type="button" class="btn btn-success" value="Guardar" />
            @*<input id="btnCancelar" type="button" class="btn btn-primary" value="Cancelar" />*@
            <a href="/Viajero/Viajero" class="btn btn-primary">Cancelar</a>
        </div>

    </div>
</form>

@section Scripts
{
    <script type="text/JavaScript">
        $(document).ready(function () {
            var idViajero = $("#IdViajero").val();

            GetViajeroByIdViajero(idViajero);


            $("#btnGuardar").click(function () {
                var nombre = $("#txtNombre").val();
                var cedula = $("#txtCedula").val();
                var direccion1 = $("#txtDireccion1").val();
                var direccion2 = $('#txtDireccion2').val();
                var ciudad = $("#txtCiudad").val();
                var estado = $("#txtEstado").val();
                var telefonoMovil = $("#txtTelefonoMovil").val();
                var telefonoFijo = $("#txtTelefonoFijo").val();

                let objViajero = {
                    nombre: nombre,
                    cedula: cedula,
                    direccion: {
                        direccion1: direccion1,
                        direccion2: direccion2,
                        ciudad: ciudad,
                        estado: estado,
                        telefonoMovil: telefonoMovil,
                        telefonoFijo: telefonoFijo
                    }
                };
                UpdateViajero(objViajero, idViajero);
                $(".removeLater").val('');
                //Go();
            });
            $("#btnCancelar").click(function () {
                // Go();
            });

        });
        //Obtiene una instancia del objeto Viajero por el IdViajero
        function GetViajeroByIdViajero(IdViajero) {

            $.ajax({
                url: 'https://localhost:44380/api/Viajero/GetViajerosByIdViajero/?IdViajero=' + IdViajero,
                type: "GET",
                data: IdViajero,
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                error: function (response) {
                    alert(response.responseText);
                    sendMessageClient("", false);
                },
                success: function (viajero) {
                    $('#txtNombre').val(viajero.Nombre);
                    $('#txtCedula').val(viajero.Cedula);
                    $('#txtDireccion1').val(viajero.Direccion.Direccion1);
                    $('#txtDireccion2').val(viajero.Direccion.Direccion2);
                    $("#txtCiudad").val(viajero.Direccion.Ciudad);
                    $("#txtEstado").val(viajero.Direccion.Estado);
                    $("#txtTelefonoMovil").val(viajero.Direccion.TelefonoMovil);
                    $("#txtTelefonoFijo").val(viajero.Direccion.TelefonoFijo);

                }
            });
        }

        //Actualiza la instancia del objeto Viajero, con los nuevos datos ingresados
        function UpdateViajero(viajero1, IdViajero) {
            var viajero = JSON.stringify(viajero1);
            $.ajax({
                url: 'https://localhost:44380/api/Viajero/UpdateViajero2/?IdViajero=' + IdViajero,
                type: "POST",
                data: viajero,
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                error: function (response) {
                    alert(response.responseText);
                    sendMessageClient("", false);
                },
                success: function (response) {
                    alert("Respuesta del servidor: " + response);
                    //sendMessageClient(formato.d, true);
                }
            });
        }
    </script>
}

AgenciaViajes.MVC/Views/Viajero/Viajero.cshtml
@{
    ViewBag.Title = "Viajero";
}

<h2>Viajero</h2>
<p>
    <a id="btnCreate" href="/Viajero/CreateViajero" class="btn btn-default btn-xs btn-primary create">Crear Nuevo Viajero</a>
</p>

<div>
    
    <table class="table table-bordered table-striped table-hover">
        <thead>
            <tr>
                <th class="hidden">IdViajero</th>
                <th>Cédula</th>
                <th>Nombre</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody id="table_viajeros"></tbody>
    </table>
</div>

<link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
@section Scripts
{
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
    <script type="text/JavaScript">
        $(document).ready(function (e) {
           
            LoadViajeros(null);
          
            
        });



        function LoadViajeros(IdViajero) {
            let tableViajero = $('#table_viajeros');

            let uri = "https://localhost:44380/api/Viajero/GetViajerosByIdViajero/?IdViajero=" + IdViajero;
            $.ajax({
                type: 'GET',
                url: uri,
                dataType: 'json',
                success: function (data) {
                    tableViajero.empty();
                    $.each(data, function (key, item) {
                        $('<tr>' +
                            '<td class="hidden"> ' + item.IdViajero + '</td > ' +
                            '<td>' + item.Cedula + '</td>' +
                            '<td>' + item.Nombre + '</td>' +
                            //1
                            //'<td>' + '<button class="btn btn-default btn-sm btn-primary" onclick="Edit(' + item.IdViajero + ')">Editar</button>'   + '</td>' +
                            //'<td>' + '<button class="btn btn-default btn-sm btn-danger " onclick="Edit(' + item.IdViajero + ')">Eliminar</button>' + '</td>' +
                            //2
                            //'<td><a href="/Viajero/EditViajero/?IdViajero=' + item.IdViajero + '"class="btn btn-default btn-xs btn-success edit">Editar</a >' + '</td >' +
                            //'<td><a href="/Viajero/DeleteViajero/?IdViajero=' + item.IdViajero + '"class="btn btn-default btn-xs btn-primary edit">Eliminar</a >' + '</td >' +

                            '<td>' + '<div class="btn-toolbar">' +'<a href="/Viajero/EditViajero/?IdViajero=' + item.IdViajero + '"class="btn btn-default btn-xs btn-success edit">Editar</a>' + 
                                     '<a href="/Viajero/DeleteViajero/?IdViajero=' + item.IdViajero + '"class="btn btn-default btn-xs btn-primary edit">Eliminar</a>'+ '</div>' + '</td >' +

                            '</tr>').appendTo($('#table_viajeros'));
                    });

                }
            });
        }

    </script>
}

AgenciaViajes.MVC/Views/Viajeros_Viajes/DeleteViajeroViaje.cshtml
@{
    ViewBag.Title = "DeleteViajeroViaje";
}

<h2>Eliminar Viajes</h2>
<input type="hidden" id="IdViaje" value="@Model" />
<input type="hidden" id="IdViajero" value="" />

<!--Viajero-->
<div class="form-group">
    <label for="inputViajero">Nombre del Viajero</label>
    <div class="form-horizontal">
        <input type="text" class="form-control removeLater" id="inputViajero" placeholder="Nombre" required readonly>
    </div>
</div>
<!--Cédula Viajero-->
<div class="form-group">
    <label for="inputCedula">Cédula del Viajero</label>
    <div class="form-horizontal">
        <input type="text" class="form-control removeLater" id="inputCedula" placeholder="Cédula del Viajero" readonly>
    </div>
</div>
<!--Código-->
<div class="form-group">
    <label for="inputCodigo">Código</label>
    <input type="text" class="form-control removeLater" id="inputCodigo" placeholder="Código" readonly>
</div>
<!--Plazas-->
<div class="form-group">
    <label for="inputPlazas">Plazas</label>
    <input type="number" class="form-control removeLater" id="inputPlazas" min="1" placeholder="Plazas" readonly>
</div>
<!--Ciudad Origen-->
<div class="form-group ">
    <label for="inputCiudadOrigen">Ciudad Origen</label>
    <select id="inputCiudadOrigen" class="form-control" readonly>
    </select>
</div>
<!--Ciudad Destino-->
<div class="form-group ">
    <label for="inputCiudadDestino">Ciudad Destino</label>
    <select id="inputCiudadDestino" class="form-control" readonly>
    </select>
</div>
<!--Ciudad Precio-->
<div class="form-group ">
    <label for="inputPrecio">Precio</label>
    <input type="text" class="form-control removeLater" id="inputPrecio" placeholder="00.00" readonly>
</div>
<!--Fecha Salida-->
<div class="form-group ">
    <label for="inputFechaSalida">Fecha Salida</label>
    <input type="text" class="form-control datepicker removeLater" id="inputFechaSalida" name="beginDate" placeholder="2019/12/1" readonly>
</div>
<!--Hora Saldia-->
<div class="form-group ">
    <label for="inputHoraSalida">Hora Salida</label>
    <input type="time" class="form-control removeLater" id="inputHoraSalida" placeholder="" readonly>
</div>
<!--Ciudad LLegada-->
<div class="form-group ">
    <label for="inputHoraLLegada">Hora Salida</label>
    <input type="time" class="form-control removeLater" id="inputHoraLLegada" readonly>
</div>

<button id="btnEliminar" type="button" class="btn btn-success">Eliminar</button>
<a id="btnCancelar" href="/Viajeros_Viajes/ViajerosViajes" class="btn btn-primary">Cancelar</a>

<link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
@section Scripts
{
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
    <script type="text/JavaScript">
        $(document).ready(function () {
            var IdViaje = $("#IdViaje").val();

            $('[readonly]').prop("disabled", true);
            $(".datepicker").datepicker({
                dateFormat: "yy-mm-dd"
            });

            LoadDropDownCiudadesOrigen(null);
            LoadDropDownCiudadesDestino(null);

            GetViajeByIdViaje(IdViaje);

            $("#btnEliminar").click(function () {
                var IdViajero = $("#IdViajero").val();
                DeleteViajero(IdViajero);
            });
        });

        //Carga las ciudades de origen
        function LoadDropDownCiudadesOrigen(IdCiduad) {
            let dropdown = $('#inputCiudadOrigen');

            let uri = "https://localhost:44380/api/Ciudades/GetCiudadesById/?IdCiudad=" + IdCiduad;
            $.ajax({
                type: 'GET',
                async: false,
                url: uri,
                dataType: 'json',
                success: function (data) {
                    dropdown.append('<option selected="true" disabled>Seleccione</option>');
                    dropdown.prop('selectedIndex', 0);
                    $.each(data, function (key, entry) {
                        dropdown.append($('<option></option>').attr('value', entry.IdCiudad).text(entry.Ciudad));
                    })
                    todos = data;
                }
            });
        }
        //Carga las ciudades de destino
        function LoadDropDownCiudadesDestino(IdCiduad) {
            let dropdown = $('#inputCiudadDestino');

            let uri = "https://localhost:44380/api/Ciudades/GetCiudadesById/?IdCiudad=" + IdCiduad;
            $.ajax({
                type: 'GET',
                async: false,
                url: uri,
                dataType: 'json',
                success: function (data) {
                    dropdown.append('<option selected="true" disabled>Seleccione</option>');
                    dropdown.prop('selectedIndex', 0);
                    $.each(data, function (key, entry) {
                        dropdown.append($('<option></option>').attr('value', entry.IdCiudad).text(entry.Ciudad));
                    })
                    todos = data;
                }
            });
        }

        //Obtiene el viaje a ser editado
        function GetViajeByIdViaje(IdViaje) {

            $.ajax({

                url: 'https://localhost:44380/api/Viajes/GetViajesByIdViaje/?IdViaje=' + IdViaje,
                type: "GET",
                async: false,
                data: IdViaje,
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                error: function (response) {
                    alert(response.responseText);
                    sendMessageClient("", false);
                },
                success: function (viaje) {
                    $("#inputViajero").val(viaje.Viajero.Nombre);
                    $("#inputCedula").val(viaje.Viajero.Cedula);
                    $("#inputCodigo").val(viaje.Codigo);
                    $("#inputPlazas").val(viaje.Plazas);
                    $("#inputCiudadOrigen").prop('selectedIndex', viaje.IdOrigen);
                    $("#inputCiudadDestino").prop('selectedIndex', viaje.IdDestino);
                    $("#inputPrecio").val(viaje.Precio);
                    $('#inputFechaSalida').val(viaje.FechaSalida);
                    $("#inputHoraSalida").val(viaje.HoraSalida);
                    $("#inputHoraLLegada").val(viaje.HoraLLegada);
                    $("#IdViajero").val(viaje.IdViajero);

                }
            });
        }


        function DeleteViajero(IdViajero) {
            var break2 = "stop";
                      
            $.ajax({
                url: 'https://localhost:44380/api/Viajero_Viajes/DeleteViajero2/?IdViajero=' + IdViajero,
                type: "GET",
                async: false,
                data: IdViajero,
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                error: function (response) {
                    alert(response.responseText);
                    sendMessageClient("", false);
                },
                success: function (viajero) {


                }
            });
        }

    </script>
}